name: Bug Report
description: Report a bug or issue
title: "[BUG] "
labels: ["bug"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug! Please provide details to help us fix it.

  - type: textarea
    id: bug-description
    attributes:
      label: Bug Description
      description: What happened? What did you expect to happen?
      placeholder: Describe the bug clearly
    validations:
      required: true

  - type: textarea
    id: reproduction-steps
    attributes:
      label: Steps to Reproduce
      description: How can we reproduce this issue?
      placeholder: |
        1. Step one
        2. Step two
        3. See error
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: What environment are you using?
      value: |
        - FueledByChai Trading Version: 
        - Java Version: 
        - Operating System: 
        - Broker:
      render: markdown
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Error Logs
      description: Please paste any relevant error logs or stack traces
      render: shell
